# Generated by Django 4.2.3 on 2023-08-01 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_alter_postcomment_options_alter_postcomment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Fue editado?'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
