# Generated by Django 4.2.3 on 2023-08-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='Selecciona una imagen relacionada para mostrar como portada del artículo', null=True, upload_to='posts', verbose_name='Imagen relacionada'),
        ),
    ]
