# Generated by Django 4.2.3 on 2023-10-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Selecciona una imagen relacionada para mostrar como portada del artículo', null=True, upload_to='posts', verbose_name='Imagen relacionada'),
        ),
    ]
