# Generated by Django 4.2.3 on 2023-10-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
