# Generated by Django 4.2.3 on 2023-10-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_sectioncontent_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectioncontent',
            old_name='title',
            new_name='parent',
        ),
    ]
