# Generated by Django 4.2.3 on 2023-10-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_rename_title_sectioncontent_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectioncontent',
            options={'verbose_name': 'Contenido de sección', 'verbose_name_plural': 'Contenidos de secciones'},
        ),
        migrations.AlterModelOptions(
            name='sectionimage',
            options={'verbose_name': 'Imagen de sección', 'verbose_name_plural': 'Imágenes de secciones'},
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Página a la que pertenece'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='content',
            field=models.TextField(verbose_name='Contenido de la sección'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='parent',
            field=models.CharField(max_length=250, verbose_name='Página a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='image',
            field=models.ImageField(upload_to='section_images/', verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sections.sectioncontent', verbose_name='Sección a la que pertenece'),
        ),
    ]
