# Generated by Django 4.2.3 on 2023-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_sectioncontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del contenido'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
