# Generated by Django 4.2.3 on 2023-10-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_sectioncontent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='css',
            field=models.TextField(blank=True, default=''),
        ),
    ]
